# Generated by Django 4.0.5 on 2022-06-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.CharField(max_length=60)),
                ('likes', models.IntegerField()),
                ('idlikes', models.IntegerField()),
                ('fave', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
    ]
