# Generated by Django 4.0.5 on 2022-06-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='idlikes',
            new_name='dislikes',
        ),
    ]
