# Generated by Django 4.0.5 on 2022-06-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameModel(
            old_name='Food',
            new_name='Foods',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
