# Generated by Django 4.0.5 on 2022-06-09 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_tags_rename_food_foods_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='tags',
            field=models.ManyToManyField(to='API.tags'),
        ),
    ]
