# Generated by Django 4.0.5 on 2022-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_foods_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='API.tags'),
        ),
    ]
