# Generated by Django 4.0.5 on 2022-06-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_foods_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='API.tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
